### ISSUE TITLE
Error when starting with matrix-connector

### ISSUE THREAD

**Issue by awesome-michael** [opsdroid/opsdroid#1159]
When I try to start opsdroid I keep getting the following error. I double checked indentation and when I delete the matrix-connector part opsdroid starts fine. 
```
opsdroid_1     | Error validating data /root/.config/opsdroid/configuration.yaml with schema /usr/src/app/opsdroid/configuration/schema.yaml
opsdroid_1     | 	connectors.1.name: 'matrix' is not a regex match.
opsdroid_1     | 	connectors.1.name: 'matrix' is not a regex match.
opsdroid_1     | 	connectors.1.name: 'matrix' is not a regex match.
opsdroid_1     | 	connectors.1.webhook-url: Required field missing
opsdroid_1     | 	connectors.1.access-token: Required field missing
opsdroid_1     | 	connectors.1.name: 'matrix' is not a regex match.
opsdroid_1     | 	connectors.1.verify-token: Required field missing
opsdroid_1     | 	connectors.1.page-access-token: Required field missing
opsdroid_1     | 	connectors.1.name: 'matrix' is not a regex match.
opsdroid_1     | 	connectors.1.mxid: 'xxx' is not a regex match.
opsdroid_1     | 	connectors.1.room: Required field missing
opsdroid_1     | 	connectors.1.rooms.main: 'xxx' is not a regex match.
opsdroid_1     | 	connectors.1.rooms.other: 'xxx' is not a regex match.
opsdroid_1     | 	connectors.1.homeserver: 'xxx' is not a regex match.
opsdroid_1     | 	connectors.1.name: 'matrix' is not a regex match.
opsdroid_1     | 	connectors.1.api-token: Required field missing
opsdroid_1     | 	connectors.1.name: 'matrix' is not a regex match.
opsdroid_1     | 	connectors.1.token: Required field missing
opsdroid_1     | 	connectors.1.name: 'matrix' is not a regex match.
opsdroid_1     | 	connectors.1.consumer_key: Required field missing
opsdroid_1     | 	connectors.1.consumer_secret: Required field missing
opsdroid_1     | 	connectors.1.oauth_token: Required field missing
opsdroid_1     | 	connectors.1.oauth_token_secret: Required field missing
opsdroid_1     | 	connectors.1.name: 'matrix' is not a regex match.
opsdroid_1     | 	connectors.1.room-id: Required field missing
opsdroid_1     | 	connectors.1.access-token: Required field missing
```

## Configuration File

```yaml
##                      _           _     _
##   ___  _ __  ___  __| |_ __ ___ (_) __| |
##  / _ \| '_ \/ __|/ _` | '__/ _ \| |/ _` |
## | (_) | |_) \__ \ (_| | | | (_) | | (_| |
##  \___/| .__/|___/\__,_|_|  \___/|_|\__,_|
##       |_|
##                   __ _
##   ___ ___  _ __  / _(_) __ _
##  / __/ _ \| '_ \| |_| |/ _` |
## | (_| (_) | | | |  _| | (_| |
##  \___\___/|_| |_|_| |_|\__, |
##                        |___/
##
## A default config file to use with opsdroid
## see https://github.com/opsdroid/opsdroid/blob/master/opsdroid/configuration/example_configuration.yaml for more config options

## Set the logging level
logging:
  level: info
  path: opsdroid.log
  console: true

## Show welcome message
welcome-message: true

## Connector modules
connectors:

  - name: websocket
    # optional
    bot-name: "mybot" # default "opsdroid"
    max-connections: 10 # default is 10 users can be connected at once
    connection-timeout: 10 # default 10 seconds before requested socket times out

  ## Matrix (core)
  - name: matrix
    # Required
    mxid: "xxx"
    password: "xxx"
    # a dictionary of multiple rooms
    # One of these should be named 'main'
    rooms:
      'main': 'xxx'
      'other': 'xxx'
    # Optional
    homeserver: "xxx"
    nick: "xxx"  # The nick will be set on startup
    room_specific_nicks: False  # Look up room specific nicknames of senders (expensive in large rooms)

## Skill modules
skills:

  ## Dance (https://github.com/opsdroid/skill-dance)
  - name: dance

  ## Hello (https://github.com/opsdroid/skill-hello)
  - name: hello

  ## Loudnoises (https://github.com/opsdroid/skill-loudnoises)
  - name: loudnoises

  ## Seen (https://github.com/opsdroid/skill-seen)
  - name: seen
```

**Comment by jacobtomlinson** [comment]
cc @Cadair @SolarDrew

**Comment by Cadair** [comment]
The config looks fine to me, I am little confused as to how this:

```
opsdroid_1     | 	connectors.1.name: 'matrix' is not a regex match.
```
is being triggered off [this](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/configuration/schema.yaml#L70) regex?

**Comment by awesome-michael** [comment]
I forgot to mention that I'm using the docker image `opsdroid/opsdroid:latest` pulled yesterday. So should be v0.16.0

**Comment by jacobtomlinson** [comment]
@Cadair yeah it's that regex. I've seen something similar when indentation has been off. There aren't any other options missing in the config are there?

**Comment by FabioRosado** [comment]
Could this be some issue with the yamale check? I remember the issue I had with Telegram(#1055) the messages seems somewhat similar to what I was getting 🤔

**Comment by awesome-michael** [comment]
Yes I'm trying to connect to my own homeserver. In fact I'm trying to connect to pantalaimon that should connect to my own homeserver as suggested in #992 ;)

I'll check if editing the regex will help with this issue.

**Comment by FabioRosado** [comment]
Please let us know but I think it will be one of these fields (if not all of then) that are causing the issues. For what I've gathered they assume you are using matrix.org only.

Please feel free to raise a PR fixing the issue if you wish otherwise i'll try to tackle it when I got the time once it has been confirmed 😄 👍

**Comment by Cadair** [comment]
>  the regex expects the string to end with :matrix.org or the homeserver to be https://matrix.org.

:see_no_evil: Why?! :scream:

**Comment by jacobtomlinson** [comment]
Ok let's roll the validation back a bit. 

I'm also not very impressed with the error handling in yamale. It seems to just blast a ton of errors at you

**Comment by FabioRosado** [comment]
Instead of reverting the validation PR how about we fix the schema? I'm with Cadair about validating the yaml beyond type - it makes sense on the required things but doesn't on other situations like this one.

Yamale allows you to just specify type like this:
```
friend:
    name: str()
```

We could check if some things are strings, lists, dicts, etc. You can also write custom validators but I'm not sure if it will be used much atm. 

I also agree that the error handling in yamale is pretty bad since it just regurgitates the errors at you and you need to cross check with the schema what is expected. (unless this is an issue with the regex validator)

**Comment by jacobtomlinson** [comment]
> Instead of reverting the validation PR how about we fix the schema?

Yeah I didn't mean revert the PR. I meant relax the rules.

**Comment by FabioRosado** [comment]
Oh sorry misunderstood the comment!

I did a quick look at yaml validators and Cerberus seems like a good way to get error handling 🤔 

What do you think? [Cerberus Usage](http://docs.python-cerberus.org/en/stable/usage.html)

**Comment by jacobtomlinson** [comment]
Would that be a replacement for yamale?

**Comment by FabioRosado** [comment]
If we want better error handling we might have to replace it yeah, not sure how it compares with yamale yet though

**Comment by awesome-michael** [comment]
okay I verified that the regex checks are responsible for the error. I changed the scheme.yaml to ```...
---                                      
matrix:                                  
  name: regex('^(?i)matrix$')            
  mxid: str(required=True)               
  password: str(required=True)           
  room: str()                      
  rooms: (include('room1'))        
  homeserver: str(required=True)   
  nick: str(required=False)        
  room_specific_nicks: bool(required=False)
  send_m_notice: bool(required=False)      
---                                        
room1:                                     
  'main': str()                            
  'other': str()                           
---  
...
```
(the rooms were checked to end with `matrix.org` too)

and altered my config to ```
 ## Matrix (core)
  - name: matrix
    # Required
    mxid: "xxx"
    password: "xxx"   
    # a dictionary of multiple rooms
    # One of these should be named 'main'
    rooms:
      'main': 'xxx'
      'other': 'xxx'
   # Optional
    homeserver: "xxx"
    nick: "xxx"  # The nick will be set on startup
    room_specific_nicks: False  # Look up room specific nicknames of senders (expensive in large rooms)
    webhook-url: ''
    access-token: ''
    verify-token: ''
    page-access-token: ''
    room: ''
    api-token: ''
    token: ''
    consumer_key: ''
    consumer_secret: ''
    oauth_token: ''
    oauth_token_secret: ''
    room-id: ''
    access-token: ''
```

I had to provide all the `Required field missing` from the error above too.
So it seems the schema check for Matrix is really broken :(
As I read through the discussion I think I won't be able to provide a PR for this.
