### ISSUE TITLE
Ctrl-C does not kill in windows

### ISSUE THREAD

**Issue by iguyking** [opsdroid/opsdroid#1190]
# Description
Trying to kill session using powershell on windows can take several minutes to register the ctrl-c

## Steps to Reproduce
opsdroid start (in a powershell window)
Hit control-c

## Expected Functionality
opsdroid should shut down

## Experienced Functionality
Can take several minutes then finally decide to shut down. 

## Versions
- **Opsdroid version:** v0.16.0
- **Python version:** 3.7.3
- **OS/Docker version:**  Windows 10

## Configuration File
```
# Show welcome message
welcome-message: true

## Skill modules
skills:

  ## Dance (https://github.com/opsdroid/skill-dance)
  - name: dance

  ## Hello (https://github.com/opsdroid/skill-hello)
  - name: hello

  ## Loudnoises (https://github.com/opsdroid/skill-loudnoises)
  - name: loudnoises

  ## Seen (https://github.com/opsdroid/skill-seen)
  - name: seen
```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.
