### ISSUE TITLE
Direct messages to Slack Users is sent via Slack Bot instead of the configured Bot User

### ISSUE THREAD

**Issue by daniccan** [opsdroid/opsdroid#1246]
# Description
Sending messages directly to Slack Users is sent by the default Slack Bot instead of the configured Bot User.

## Steps to Reproduce
1. Configure Slack Connector in Opsdroid.
2. Send a message to a user instead of a channel by setting the `message.target` value (e.g. @someuser)

## Expected Functionality
The message should be sent to the user via the bot user whose API token we have configured.

## Experienced Functionality
The message is sent to the user via the default Slack Bot.

## Versions
- **Opsdroid version:** master branch in git
- **Python version:** 3.6.8
- **OS/Docker version:** Ubuntu 18.04 LTS

## Configuration File
Please include your version of the configuration file below.

```yaml
# Your code goes here.
welcome-message: true

connectors:
  - name: slack
    api-token: "<Bot OAuth Token>"

skills:
  - name: myskill
    path: /path/to/myskill

```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.
