### ISSUE TITLE
Add get module convenience methods

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#1345]
Sometimes it is helpful to be able to grab a connector, database, etc from within your skill.

You may wish to call `connector.send` on a specific connector, or use the `database.client` to directly interact with the database (just don't mess with the `opsdroid` table).

Currently you can access the lists of modules from the attributes `opsdroid.connectors`, `opsdroid.databases`, etc. However to grab a specific connector or database you end up doing a list compehension.

```python
[slack] = [connector for connector in self.opsdroid.connectors if connector.name == "slack"]
await slack.send(Message("Hello world"))
```

It would be nice to have some convenience methods such as `get_connector` and `get_database` in the `opsdroid` object to make accessing these easier. For example

```python
slack = self.opsdroid.get_connector("slack")
await slack.send(Message("Hello world"))

sqlite = self.opsdroid.get_database("sqlite")
cur = await sqlite.client.cursor()
await cur.execute("INSERT INTO students (name) VALUES ('" + name + "');")  # Beware of Bobby Tables
await self.client.commit()
```

**Comment by Cadair** [comment]
If it doesn't already work, we should allow the `connector=` kwarg to `Event` to be a string, which gets converted into the connector based on the name. This would let you do send easily by doing something like
```python
opsdroid.send(Message("hello", connector="slack"))
```

**Comment by jacobtomlinson** [comment]
Ooh yes definitely!

**Comment by jerrykan** [comment]
This would be a really useful feature. However is there a potential problem with just using the connector name as the key? What if there are multiple connectors of the same type?

Maybe there needs to be some sort of `id` associated with the connector configuration? ie:
```
connectors:
    - name: matrix
      id: connector1
      mxid: '@user1:matrix.org'
      password: xxx
      rooms:
        'room1': '#room1:matrix.org'
    - name: matrix
      id: connector2
      mxid: '@user1:matrix.org'
      password: xxx
      rooms:
        'room1': '#room1:matrix.org'
```
It would then be used something like:
```
opsdroid.send(Message("hello", connector="connector1"))
```

However, if we were willing to make a backward incompatible change, then changing the existing `name` to `type` might be preferable. ie:
```
connectors:
    - name: connector1
      type: matrix
      ...

    - name: connector1
      type: matrix
      ...
```
There may be a way to fudge this a bit to provide some backwards compatibility (ie `type` defaults to the value of `name` if not provided), but for the moment I'm just putting some general thoughts out there.

**Comment by jacobtomlinson** [comment]
You cannot set a duplicate name. Opsdroid tries to autodetect which module you want based on the name. Setting the name to `matrix` will set the module property to `opsdroid.connector.matrix`. So for multiple matrix connectors you should set something like this.

```
connectors:
  - name: matrix

  - name: othermatrix
    module: opsdroid.connector.matrix
```
