### ISSUE TITLE
Configure skill specific default connectors and targets

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#1349]
Currently you can specify a default connector and default targets for Opsdroid to message in. If not specified the default connector is the first connector specified in your config and the default targets is a sensible default set by the connector.

Alternatively you can be explicit in your config:

```yaml
connectors:
  websocket: {}  
  slack:
    default: true
    default-room: "#random"
```

In this config we are telling `slack` to be the default and changing the default target to `#random`.

This means we can have skills like this:

```python
from opsdroid.skill import Skill
from opsdroid.matchers import match_crontab
from opsdroid.events import Message

class HelloSkill(Skill):
    @match_crontab("0 1 * * *")
    async def hello(self, event):
        await opsdroid.send(Message(text="It's 1am!"))
```

We haven't specified where the `Message` should be sent so the defaults are used.

However @quulah has raised a use case where it would be good to be able to set these defaults on a per skill basis. Currently, you can do this yourself in your skill with something like the following.

```python
from opsdroid.skill import Skill
from opsdroid.matchers import match_crontab
from opsdroid.events import Message

class HelloSkill(Skill):
    @match_crontab("0 1 * * *")
    async def hello(self, event):
        # Get the connector and target
        connector_name = self.config.get("default-connector", self.opsdroid.default_connector)
        connector = opsdroid.get_connector(connector_name)  # This assumes #1345 is done, today it is much less pleasant
        target = self.config.get("default-target", connector.default_target)

        # Send the message and be explicit about the connector and target
        await opsdroid.send(Message(text="It's 1am!", connector=connector, target=target))

        # Alternatively you could call send directly on the connector
        await connector.send(Message(text="It's 1am!", target=target))
```

The discussion I want to have here is should we look at allowing skill specific default connectors and targets?

For example:

```yaml
connectors:
  websocket: {}  
  slack:
    default-room: "#random"

skills:
  awesomeskill:
    path: "/some/path"
    default-connector: "slack"
  functionalskill:
    path: "/some/other/path"
    default-connector: "slack"
    default-target: "#general"
```

With this configuration we would need `self.opsdroid.default_connector` and `connector.default_room` to return different values depending on the skill which is calling it.
