### ISSUE TITLE
Telegram connector needs update for event message

### ISSUE THREAD

**Issue by TonyRoomZ** [opsdroid/opsdroid#1354]
# Description
The telegram connector uses message.target['id'] instead of message.target.  This leads to problems when trying to use default_target per normal configuration and usage of the event flow logic.

## Steps to Reproduce
Setup telegram as the default connector... call the telegram connector.send with a target...  
```
await self.opsdroid.send(Message(text='hello', target='<useridhere>') 
```
The default_target is also always None.
```
await self.opsdroid.send(Message(text='hello')  
```
You can hack around it with..
```
sillytarget = { 'id': <useridhere> }
await self.opsdroid.send(Message(text='hello', target=sillytarget) 
```
## Expected Functionality
message.target should work like the other core connectors

## Experienced Functionality
Errors out.
```
opsdroid    | ERROR opsdroid.connector.telegram.send_message(): Unable to respond.   
```
## Versions

- opsdroid: latest/stable
- python 3.7.6
- docker image: opsdroid/opsdroid:latest

## Configuration File
```yaml
connectors:
## Telegram (core)
  telegram:
    token: "......"
   # optional
    update-interval: 0.5  # Interval between checking for messages
    whitelisted-users:  # List of users who can speak to the bot, if not set anyone can speak
      - ......
```
## Additional Details
None
