### ISSUE TITLE
Connection through pantalaimon is failing

### ISSUE THREAD

**Issue by awesome-michael** [opsdroid/opsdroid#1368]
# Description
I tried to run Opsdroid v0.17.x from Docker-Hub through pantalaimon which worked before. But now Opsdroid keeps failing with following error:

```

opsdroid_1     |   File "/usr/local/lib/python3.7/site-packages/opsdroid/connector/matrix/connector.py", line 148, in connect
opsdroid_1     |     set_presence="online",
opsdroid_1     |   File "/usr/local/lib/python3.7/site-packages/matrix_api_async/api_asyncio.py", line 67, in _send
opsdroid_1     |     code=response.status, content=await response.text())
opsdroid_1     | matrix_client.errors.MatrixRequestError: 401: {"errcode":"M_UNKNOWN_TOKEN","error":"Unrecognised access token","soft_logout":false}
```

**Comment by FabioRosado** [comment]
Thank you for raising this issue, could you show your config as well? I’m wondering if something broke when we moved to dicts

**Comment by awesome-michael** [comment]
sure.. my config looks like this:

```
## Set the logging level
logging:
  level: info
  path: opsdroid.log
  console: true

## Show welcome message
welcome-message: true

## Connector modules
connectors:

  - name: websocket
    # optional
    bot-name: "mybot" # default "opsdroid"
    max-connections: 10 # default is 10 users can be connected at once
    connection-timeout: 10 # default 10 seconds before requested socket times out

  ## Matrix (core)
  - name: matrix
    # Required
    mxid: "@bot:example.com"
    password: "xxx"
    # a dictionary of multiple rooms
    # One of these should be named 'main'
    rooms:
      main: '#public:example.com'
      other: '#testraum:example.com'
      third: '#bot-test:example.com'
   # Optional
    homeserver: "http://pantalaimon:8008"
    nick: "Mynickname"  # The nick will be set on startup
    room_specific_nicks: False  # Look up room specific nicknames of senders (expensive in large rooms)

## Skill modules
skills:

  - name: poll
    path: /root/skills/poll
    no-cache: true

  - name: hello
    path: /root/skills/hello
    no-cache: true

```
