### ISSUE TITLE
Constraints don't apply to non-Message events

### ISSUE THREAD

**Issue by jerrykan** [opsdroid/opsdroid#1381]
# Description
It seems that constrains don't apply to non-Message events.

## Steps to Reproduce
```python
class ExampleSkill(Skill):

    @match_event(JoinRoom)
    @constrain_rooms(['room1'])
    async def user_join(self, event):
        print('User joined {}'.format(event.target))
```

## Expected Functionality
The `user_join()` skill method would only run if a user joined `room1`

## Experienced Functionality
The `user_join()` skill method is run when a user joins any room the connector is configured to join.

## Versions
- **Opsdroid version:** 7282a5da06
- **Python version:** 3.7.6
- **OS/Docker version:** Linux/Debian (testing)

## Configuration File
```yaml
connector:
  - name: matrix
    mxid: '@user:matrix.org'
    password: xxx
    nick: 'User'
    rooms:
      'room1': <room id>
      'room2': <room id>
```
