### ISSUE TITLE
Duplicated shell prompt 

### ISSUE THREAD

**Issue by QidongS** [opsdroid/opsdroid#1407]
# Description
When I run the hello skill from the shell, I found duplicated shell prompt output. I think there's some issue with the shell connector. 

## Steps to Reproduce
```
qidong@ubuntu:~/Documents/opsdroid$ opsdroid start
mybot> hello
Hello qidong
mybot> mybot>
```

## Expected Functionality
There should be only one prompt printed after the skill response. 

## Experienced Functionality
One extra prompt is printed. 

## Configuration File

```yaml
logging:
  console: false

connectors:
  websocket:
    bot-name: "mybot"
    max-connections: 10
    connection-timeout: 10
  
  shell:
    bot-name: "mybot"

skills:
  ## Hello (https://github.com/opsdroid/skill-hello)
  hello: {}
```
