### ISSUE TITLE
ERROR opsdroid.connector.slack.events: Username lookup failed for 'user'.

### ISSUE THREAD

**Issue by chillipeper** [opsdroid/opsdroid#1617]
# Description
Every time a message is sent inside a thread in Slack, the RTM API sends a message event with subtype "message_replied" that at the moment is not properly handled.

This is causing Opsdroid to call unnecessarily the [`_get_user_name` ](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/connector/slack/events.py#L195) method in the slack connector, which at the same time ends in an unnecessary call to the Slack API.

Everytime a response is originated inside a thread the logs show the message:
```
ERROR opsdroid.connector.slack.events: Username lookup failed for 'user'.
ERROR opsdroid.connector.slack.events: Username lookup failed for 'user'.
```

## Steps to Reproduce
Use the hello skill to reply inside a thread in Slack

## Expected Functionality
The subtype "message_replied"  has to be properly handled

## Experienced Functionality

Everytime a response is originated inside a thread the logs show the message:
```
ERROR opsdroid.connector.slack.events: Username lookup failed for 'user'.
ERROR opsdroid.connector.slack.events: Username lookup failed for 'user'.
```

## Versions
- **Opsdroid version: v0.19.0+17.g78046f2.dirty
- **Python version: 3.8
- **OS/Docker version:Ubuntu 20.04

## Configuration File
```
logging:
  level: info

welcome-message: true

connectors:
  - name: websocket
  - name: slack
    token: $SLACK_TOKEN
    start_thread: true

skills:
  hello: {}
```
