### ISSUE TITLE
E2EE - Matrix Connector

### ISSUE THREAD

**Issue by ironoa** [opsdroid/opsdroid#1676]
# Description
I would need to be able to use E2EE with the Matrix connector. My skill is fully working in an unencrypted room (read from the chat, write to the chat), but in an encrypted room my skill is only capable of writing to the chat.

Here it's mentioned that the E2EE is supported: https://docs.opsdroid.dev/en/latest/connectors/matrix.html
That documentation appears only if you select version "latest", if you select v0.19.0 it disappears. But in DockerHub the v0.19.0 and the latest tags seems to coincide ( 5 months ago ) https://hub.docker.com/r/opsdroid/opsdroid/tags

## Support Request
1) Is E2EE on the matrix connector supported on version v0.19.0 or not ?
2) Installing the "matrix-nio[e2e]" and the "libolm" libraries is not straightforward in the opsdroid/opsdroid:v0.19.0 docker image. Could you please help me with that ?
3) After having installed the two libraries mentioned above, should I expect the E2EE functionality starts to work out of the box ? If not, could you guide me please ? 

## Expected Functionality
My skills should be capable of read messages even from encrypted matrix rooms, as it is for the unencrypted rooms.

## Experienced Functionality
My skills can only write messages to encrypted rooms. That messages appear with a warning: Unencrypted 
![image](https://user-images.githubusercontent.com/25957738/99947218-ef0e9300-2d77-11eb-9de4-e7b9cc60f91b.png)

## Versions
- **Opsdroid version: v0.19.0**
- **Docker version: version 19.03.8**

## Configuration File
Please include your version of the configuration file below.

```yaml
web:
  host: '0.0.0.0'
  port: 8080
databases:
  sqlite:
    path: "/app/db/finance.db"  
    table: "finance"  
skills:
  - name: eventmanager
    path: /app/skills/skill-eventmanager
connectors:
  matrix:
    mxid: "XXX"
    password: "XXX"
    rooms:
      "main": "myEncryptedRoomId:XXX.XXX"
    homeserver: XXX
    store_path: "/app/store/"
```

```Dockerfile
FROM opsdroid/opsdroid:v0.19.0
RUN adduser -D -g '' opsdroid
COPY skills /app/skills
USER opsdroid
```

Thanks
