### ISSUE TITLE
opsdroid has errors with matrix connector

### ISSUE THREAD

**Issue by aermike** [opsdroid/opsdroid#1779]
# Description
Please include a summary of the issue.
DEBUG opsdroid.loader: Loaded connector: opsdroid.connector.matrix.
DEBUG opsdroid.core: Loaded 4 skills.
DEBUG asyncio: Using selector: EpollSelector
Traceback (most recent call last):
  File "/usr/local/bin/opsdroid", line 33, in <module>
    sys.exit(load_entry_point('opsdroid==0.22.0', 'console_scripts', 'opsdroid')())
  File "/home/mike/.local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/mike/.local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/mike/.local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mike/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mike/.local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/mike/.local/lib/python3.9/site-packages/opsdroid/cli/start.py", line 43, in start
    opsdroid.run()
  File "/home/mike/.local/lib/python3.9/site-packages/opsdroid/core.py", line 166, in run
    self.sync_load()
  File "/home/mike/.local/lib/python3.9/site-packages/opsdroid/core.py", line 215, in sync_load
    self.eventloop.run_until_complete(self.load())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/mike/.local/lib/python3.9/site-packages/opsdroid/core.py", line 226, in load
    await self.setup_connectors(self.modules["connectors"])
  File "/home/mike/.local/lib/python3.9/site-packages/opsdroid/core.py", line 371, in setup_connectors
    connector = cls(connector_module["config"], self)
  File "/home/mike/.local/lib/python3.9/site-packages/opsdroid/connector/matrix/connector.py", line 91, in __init__
    self.rooms = self._process_rooms_dict(config["rooms"])
  File "/home/mike/.local/lib/python3.9/site-packages/opsdroid/connector/matrix/connector.py", line 139, in _process_rooms_dict
    for name, room in rooms.items():
AttributeError: 'NoneType' object has no attribute 'items'

## Steps to Reproduce
Please also include relevant information and steps to reproduce the bug/issue.

## Expected Functionality
Explain what should happen.

## Experienced Functionality
Explain what happened instead(Please include the debug log).

## Versions
- **Opsdroid version:** -  latest
- **Python version:** -  python --version Python 2.7.16
                                  python3 --version Python 3.7.3

- **OS/Docker version:**

## Configuration File
Please include your version of the configuration file below.

```yaml  ## Matrix (core)
 matrix:
#    # Required
   mxid: "@robot:matrix.company.ro"
   password: "somepassword"
#    # A dictionary of multiple rooms
#    # One of these should be named 'main'
   rooms:
    'main': '#main:matrix.company.ro'
    'otherroom': '#otherroom:matrix.company.ro'
#      'other': '#element-web:matrix.org'
#    # Optional
   homeserver: "https://matrix.company.ro"
   nick: "robot"  # The nick will be set on startup
   room_specific_nicks: True  # Look up room specific nicknames of senders (expensive in large rooms)
   enable_encryption: True
   device_name: "opsdroid"
   device_id: "opsdroid" # A unique string to use as an ID for a persistent opsdroid device
#    store_path: "path/to/store/" # Path to the directory where the matrix store will be saved
#

# Your code goes here.

```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.
