### ISSUE TITLE
no  response with shell connector in docker

### ISSUE THREAD

**Issue by yypptest** [opsdroid/opsdroid#1828]
# Description
I'm new to opsdroid. I installed opsdroid using docker and configured with shell connector, but there's no response for the command.

## Steps to Reproduce
1. Created the configuration.yaml as below:
```
## Set the logging level
logging:
  console: false

## Show welcome message
welcome-message: true

## Configure the web server
web:
  host: '0.0.0.0'
  port: 8080

## Connector modules
connectors:
  shell:
    bot-name: "mybot" # default "opsdroid"

## Skill modules
skills:

  ## Dance (https://github.com/opsdroid/skill-dance)
  dance: {}

  ## Hello (https://github.com/opsdroid/skill-hello)
  hello: {}

  ## Loudnoises (https://github.com/opsdroid/skill-loudnoises)
  loudnoises: {}

  ## Seen (https://github.com/opsdroid/skill-seen)
  seen: {}
```
2. installed opsdroid with docker with below steps, configuration.yaml is located in the path /images/opsdroid
```
docker pull opsdroid/opsdroid:latest
docker run --rm -it -v /images/opsdroid:/root/.config/opsdroid opsdroid/opsdroid:latest
```
3. Then run "hi/hello" for testing, no response from the bot. When run Ctl+C, it reports error 
```
[root@sretooling-chatops-2-inf opsdroid]# docker run --rm -it -v /images/opsdroid/:/root/.config/opsdroid opsdroid/opsdroid:latest
mybot> hi
hello
^CERROR: Unhandled exception in opsdroid, exiting...
Caught exception
{'message': 'Task exception was never retrieved', 'exception': AttributeError("'ConnectorShell' object has no attribute 'user'"), 'future': <Task finished name='Task-10' coro=<ConnectorShell._parse_message() done, defined at /usr/local/lib/python3.8/site-packages/opsdroid/connector/shell/__init__.py:90> exception=AttributeError("'ConnectorShell' object has no attribute 'user'")>}
```

## Expected Functionality
The command "hi/hello" should have response 

## Experienced Functionality
Explain what happened instead(Please include the debug log).

## Versions
- **Opsdroid version:** 0.23.0
- **Python version:** docker
- **OS/Docker version:** docker vesion: 20.10.6

## Configuration File
Please include your version of the configuration file below.

```yaml
# Your code goes here.

```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.
