### ISSUE TITLE
Use pre-trained Rasa model.

### ISSUE THREAD

**Issue by DAMO238** [opsdroid/opsdroid#1853]
# Description
There is no option to take a pre-trained Rasa model (perhaps trained on a more powerful machine) and use that for predictions instead of training a new model each time opsdroid is started.

## Expected Functionality
There should be a configuration option under something such as `parsers->rasanlu->no-train` which by default is false, but can be set to true in order to prevent opsdroid sending the request to re-train each time.

## Experienced Functionality
No such option exists.

## Versions
- **Opsdroid version:**0.23.0
- **Python version:**3.9.2
- **OS/Docker version:**Debian 11

**Comment by FabioRosado** [comment]
Thank you for raising this issue @DAMO238  is this still the case? I'm just catching up on the convo in our community channel

**Comment by DAMO238** [comment]
Yes, this is still an issue. I used a work around by commenting out the line of code responsible for training rasa in my installation, but this is more of a hacky work around than a solution. There seem to already be functions for loading a model and checking if rasa already has a model loaded. I propose that opsdroid should check if rasa has a model loaded, and then, only if there is no model, check the configuration to see if a model should be loaded and then finally, fallback to training the model (current functionality).

**Comment by FabioRosado** [comment]
Ah gotcha thank you again for raising this and for the clarification 👍

**Comment by FabioRosado** [comment]
Can I ask you for an example on your configuration? Are you providing an intentions yaml file with your rasa config?

Looking at the docs it seems that we only train the model if you provide the intents yaml file.

**Comment by DAMO238** [comment]
I am not providing an intentions yaml file, as I trained my model on a different computer and then copied it onto my server. Here is the rasa section of my opsdroid config:

```
parsers:
        rasanlu:
                url: http://localhost:5005
                models-path: models
                token: SUPER_SECRET_TOKEN
                min-score: 0.8
```

Then my rasa config:

```
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
   - name: SpacyNLP
     model: en_core_web_md
     case_sensitive: False
   - name: SpacyTokenizer
   - name: SpacyFeaturizer
   - name: SpacyEntityExtractor
   - name: RegexFeaturizer
     #   - name: RegexEntityExtractor
   - name: LexicalSyntacticFeaturizer
   - name: CountVectorsFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
   - name: DIETClassifier
     epochs: 100
     constrain_similarities: true
   - name: EntitySynonymMapper
   - name: ResponseSelector
     epochs: 100
     constrain_similarities: true
   - name: FallbackClassifier
     threshold: 0.3
     ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
```

This is an exact clone of the config used to create the model so that rasa can load the model trained on my laptop.
