### ISSUE TITLE
User configurable connection for mongo-based databases

### ISSUE THREAD

**Issue by bparbhu** [opsdroid/opsdroid#1859]
So the pymongo client has a multitude of ways for connecting to different mongo services

So for MongoDB Atlas users the connection string is given as such 
for python connections to the mongo db atlas 

`mongodb+srv://<username>:<password>@<cluster-name>.mongodb.net/myFirstDatabase`

In making the mongo connection to be user configurable we can specify different types of mongo services versus
just asking for the basic connection arguments like port, user name,  pass, and also we can give users an easier way to connect versus making assumptions about the type of mongodb the kinds of credentials they might have. 

As long as the pymongo client accepts the connection and connects the user to the database and the collection they want I think this would be great!

Thanks again guys!

**Comment by jacobtomlinson** [comment]
Thanks for raising this @bparbhu.

Looking at your connection URL you would configure the database like this.

```yaml
databases:
  mongo:
    host:                       "<cluster-name>.mongodb.net"
    port:                       "12345" 
    database:                   "myFirstDatabase"
    collection:                 "opsdroid"
    user:                       "<username>"
    password:                   "<password>"
```

Which we format into a string for you.

https://github.com/opsdroid/opsdroid/blob/ee43c560560bc5cff08062839200e77724945e6b/opsdroid/database/mongo/__init__.py#L52-L54

However I note that we have the protocol `mongodb://` hardcoded and your connection string has `mongodb+srv://`. Which is probably why things aren't working for you. We should make the protocol configurable too.
