### ISSUE TITLE
Matrix_cache folder get's permission denied.

### ISSUE THREAD

**Issue by Sleuth56** [opsdroid/opsdroid#1873]
# Description
Now that the opsdroid container runs as an un-privilaged user when opsdroid attempts to create the Matrix_cache folder it gets a permission denied error.
I'm not sure how to fix this or if it's even possible. Might as well bring it up though just in case.

## Steps to Reproduce
For the sake of reproduction I'm going to include one of my skills.
`git clone https://gitlab.com/Sleuth56/imageofthehour.git`
`cd imageofthehour`
configure opsdroid to use matrix. using `configuration.yaml` file
`docker-compose up`

## Expected Functionality
Opsdroid should create the 'Matrix_cache' folder without error

## Experienced Functionality
```
[user@computer imageofthehour]$ docker-compose up
[+] Running 2/0
 ⠿ Network imageofthehour_default       Created                                                                           0.0s
 ⠿ Container imageofthehour-opsdroid-1  Created                                                                           0.0s
Attaching to imageofthehour-opsdroid-1
imageofthehour-opsdroid-1  | Traceback (most recent call last):
imageofthehour-opsdroid-1  |   File "/usr/local/bin/opsdroid", line 8, in <module>
imageofthehour-opsdroid-1  |     sys.exit(cli())
imageofthehour-opsdroid-1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
imageofthehour-opsdroid-1  |     return self.main(*args, **kwargs)
imageofthehour-opsdroid-1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
imageofthehour-opsdroid-1  |     rv = self.invoke(ctx)
imageofthehour-opsdroid-1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
imageofthehour-opsdroid-1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
imageofthehour-opsdroid-1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
imageofthehour-opsdroid-1  |     return ctx.invoke(self.callback, **ctx.params)
imageofthehour-opsdroid-1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
imageofthehour-opsdroid-1  |     return __callback(*args, **kwargs)
imageofthehour-opsdroid-1  |   File "/usr/local/lib/python3.9/site-packages/opsdroid/cli/start.py", line 36, in start
imageofthehour-opsdroid-1  |     config = load_config_file(config_path)
imageofthehour-opsdroid-1  |   File "/usr/local/lib/python3.9/site-packages/opsdroid/configuration/__init__.py", line 96, in load_config_file
imageofthehour-opsdroid-1  |     config_path = get_config_path(config_paths)
imageofthehour-opsdroid-1  |   File "/usr/local/lib/python3.9/site-packages/opsdroid/configuration/__init__.py", line 74, in get_config_path
imageofthehour-opsdroid-1  |     config_path = create_default_config(DEFAULT_CONFIG_PATH)
imageofthehour-opsdroid-1  |   File "/usr/local/lib/python3.9/site-packages/opsdroid/configuration/__init__.py", line 41, in create_default_config
imageofthehour-opsdroid-1  |     shutil.copyfile(EXAMPLE_CONFIG_FILE, config_path)
imageofthehour-opsdroid-1  |   File "/usr/local/lib/python3.9/shutil.py", line 264, in copyfile
imageofthehour-opsdroid-1  |     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
imageofthehour-opsdroid-1  | PermissionError: [Errno 13] Permission denied: '/home/opsdroid/.config/opsdroid/configuration.yaml'
imageofthehour-opsdroid-1 exited with code 1
```

## Versions
- **Opsdroid version:** v0.23.0+26.g813e274
- **Python version:** 3.9.6
- **OS/Docker version:** 20.10.10, build b485636f4b

## Configuration File
Please include your version of the configuration file below.
Matrix account info has been redacted.
```yaml
welcome-message: false

connectors:
  matrix:
    mxid: "@ImageOfTheHour:matrix.org"
    password: ""
    rooms:
      'main': '!room:matrix.org'
    homeserver: "https://matrix.org"
    nick: "ImageOfTheHour"  # The nick will be set on startup
    enable_encryption: True
    device_name: "opsdroid"
    device_id: "opsdroid" # A unique string to use as an ID for a persistent opsdroid device
    store_path: "/home/opsdroid/.config/opsdroid/Matrix_cache"

skills:
  ImageOfTheHour:
    path: /home/opsdroid/.config/opsdroid/Skill

web:
  host: '0.0.0.0'
  port: 8080

```
