### ISSUE TITLE
Matrix Connector cannot import name Iterable from Collections

### ISSUE THREAD

**Issue by walkrr** [opsdroid/opsdroid#1928]
When using the matrix connector on python 3.10, the module fails to start. When verbose logging is enabled, an error is logged in the console:

## Steps to Reproduce
To reproduce enable the matrix connector on a computer running python 3.10

## Versions
- **Opsdroid version: 0.26.0**
- **Python version: 3.10.4**
- **OS/Docker version: Arch Linux, Linux-Zen 5.18 kernel**

## Configuration File
Please include your version of the configuration file below.

```yaml
##                      _           _     _
##   ___  _ __  ___  __| |_ __ ___ (_) __| |
##  / _ \| '_ \/ __|/ _` | '__/ _ \| |/ _` |
## | (_) | |_) \__ \ (_| | | | (_) | | (_| |
##  \___/| .__/|___/\__,_|_|  \___/|_|\__,_|
##       |_|
##                   __ _
##   ___ ___  _ __  / _(_) __ _
##  / __/ _ \| '_ \| |_| |/ _` |
## | (_| (_) | | | |  _| | (_| |
##  \___\___/|_| |_|_| |_|\__, |
##                        |___/
##
## A default config file to use with opsdroid

## Set the logging level
# logging:
#   level: info
#   path: opsdroid.log
#   rich: false
#   console: true
#   extended: false
#   timestamp: true
#   formatter: "%(levelname)s: %(message)s"
#   filter:
#     whitelist:
#       - opsdroid.core
#     blacklist:
#       - opsdroid.loader

## Set the location for opsdroid to install modules
# module-path: "."

## Configure the language to use
#lang: 'en'

## Show welcome message
welcome-message: true

## Configure the web server
# web:
#   host: '127.0.0.1'
#   disable_web_index_handler_in_root: true
#   port: 8080
#   ssl:
#     cert: /path/to/cert.pem
#     key: /path/to/key.pem
#   webhook-token: "aabbccddee"

## Parsers
# parsers:
#
#  ## Rasanlu (http://docs.opsdroid.dev/en/stable/skills/matchers/rasanlu.html)
#  rasanlu:
#    url: http://localhost:5000
#    project: opsdroid
#    token: 85769fjoso084jd
#    min-score: 0.8
#    train: False # Defaults to True
#
#  ## Dialogflow (http://docs.opsdroid.dev/en/stable/skills/matchers/dialogflow.html)
#  dialogflow:
#    project-id: <project id>
#    min-score: 0.6
#
#  ## Regex (http://docs.opsdroid.dev/en/stable/skills/matchers/regex.html)
#  regex:
#    enabled: true
#
#  ## Parse_format (http://docs.opsdroid.dev/en/stable/skills/matchers/parse_format.html)
#  parse_format:
#    enabled: true
#
#  ## Wit.ai (http://docs.opsdroid.dev/en/stable/skills/matchers/wit.ai.html)
#  witai:
#    token: XJF475SKGITJ98KHFO
#    min-score: 0.6
#
#  ## Luis.ai (http://docs.opsdroid.dev/en/stable/skills/matchers/luis.ai.html)
#   luisai:
#     appid: "<application-id>"
#     appkey: "<subscription-key>"
#     verbose: True
#     min-score: 0.6
#
#  ## Crontab (http://docs.opsdroid.dev/en/stable/skills/matchers/crontab.html)
#  crontab:
#    enabled: true
#
#  ## Sapcai (http://docs.opsdroid.dev/en/stable/skills/matchers/sapcai.html)
#  sapcai:
#    token: 85769fjoso084jd
#    min-score: 0.8
#
#  ## Watson (http://docs.opsdroid.dev/en/stable/skills/matchers/watson.html)
#  watson:
#    gateway: gateway-fra # Required
#    assistant-id: '74yhfhis9-kfirj1e-jfir34-kfdir345' # Required
#    token:  XJF475SKGITJ98KHFO # Required
#    min-score: 1.0
#
#
## Connector modules
connectors:
  websocket:
    # optional
    bot-name: "mybot" # default "opsdroid"
    max-connections: 10 # default is 10 users can be connected at once
    connection-timeout: 10 # default 10 seconds before requested socket times out
  # Uncomment the connector(s) that you wish opsdroid to work on
#
#  ## Twitter (https://github.com/opsdroid/connector-twitter)
#  twitter:
#    # required
#    consumer_key: "zyxw-abdcefghi-12345"
#    consumer_secret: "zyxw-abdcefghi-12345-zyxw-abdcefghi-12345"
#    oauth_token: "zyxw-abdcefghi-12345-zyxw-abdcefghi-12345"
#    oauth_token_secret: "zyxw-abdcefghi-12345-zyxw-abdcefghi-12345"
#    # optional
#    enable_dms: true  # Should the bot respond to Direct Messages
#    enable_tweets: true  # Should the bot respond to tweets
#
# ## Twitch (core)
#  twitch:
#   # required
#   code: "hfu923hfks02nd2821jfislf" # Code obtained from the first OAuth step
#   client-id: "e0asdj48jfkspod0284"
#   client-secret: "kdksd0458j93847j"
#   channel: theflyingdev # Broadcaster channel
#   redirect: http://localhost # Url to be passed to get oath token - defaults to localhost
#   forward-url: 'http://94jfsd9ff.ngrok.io' # Either an URL provided by a forwarding service or an exposed ip address
#   # optional
#   webhook-lease-seconds: 86400 # how long for webhooks to expire
#   always-listening: false # Turn on to connect to the chat server even if stream is offline.
#
#  ## Webexteams (core)
#  webexteams:
#    # required
#    webhook-url: http(s)://<host>:<port>  # Url for Webex Teams to connect to your bot
#    token: <your bot access token>  # Your access token
#
#  ## Facebook (core)
#  facebook:
#    # required
#    verify-token: aabbccddee
#    page-access-token: aabbccddee112233445566
#    # optional
#    bot-name: "mybot" # default "opsdroid"
#
#  ## Matrix (core)
  matrix:
    # Required
    mxid: "******"
    password: "*******"
    # A dictionary of multiple rooms
    # One of these should be named 'main'
    rooms:
    'main': '*******'
#    # Optional
#    homeserver: "https://matrix.org"
#    nick: "Botty McBotface"  # The nick will be set on startup
#    room_specific_nicks: False  # Look up room specific nicknames of senders (expensive in large rooms)
#    device_name: "opsdroid"
#    device_id: "opsdroid" # A unique string to use as an ID for a persistent opsdroid device
#    store_path: "path/to/store/" # Path to the directory where the matrix store will be saved
#
#  ## Mattermost (core)
#  mattermost:
#    # Required
#    token: "zyxw-abdcefghi-12345"
#    url: "mattermost.server.com"
#    team-name: "myteam"
#    # Optional
#    scheme: "http" # default: https
#    port: 8065 # default: 8065
#    ssl-verify: false # default: true
#    connect-timeout: 30 # default: 30
#
#  ##GitLab (core)
#  gitlab:
#    # Optional but recomended
#    webhook-token: <your token>
#    # Required if sending message to gitlab
#    token: <personal access token>
#  ## Github (core)
#  github:
#    # required
#    token: aaabbbcccdddeee111222333444
#    secret: <your secret>
#
#  ## Gitter (core)
#  gitter:
#    # Required
#    room-id: 1239kr
#    token: jdr-3i4p-dk
#    # Optional
#    bot-name: opsdroid
#
#  ## Telegram (core)
#  telegram:
#    # required
#    token: "123456789:ABCDEFGHIJKLMNOPQRSTUVWXYZ-ZYXWVUT"  # Telegram bot token
#    # optional
#    bot-name: opsdroid  # Name to be used by the bot in some replies, defaults to opsdroid
#    reply-unauthorized: True # Should the bot reply to unauthorized users?
#    whitelisted-users:  # List of users who can speak to the bot, if not set anyone can speak
#      - user1
#      - user2
#
#  ## Teams (core)
#  teams:
#    # Required
#    app-id: "yourappid"
#    password: "yourpassword"
#    # Optional
#    bot-name: "mybot" # default "opsdroid"
#  ## Slack (core)
#  slack:
#    # required
#    bot-token: "zyxw-abdcefghi-12345"
#    # optional
#    socket-mode: false # default true
#    app-token: "xapp-abdcfkje-12345" # socket-mode needs to be true
#    start-thread: true # default false, if true opsdroid will reply in a thread
#    bot-name: "mybot" # default "opsdroid"
#    default-room: "#random" # default "#general"
#    icon-emoji: ":smile:" # default ":robot_face:"
#
#  ## Rocketchat (core)
#  rocketchat:
#    # required
#    user-id: "1ioKHDIOD"
#    token: "zyxw-abdcefghi-12345"
#    # optional
#    bot-name: "mybot" # default "opsdroid"
#    default-room: "random" # default "general"
#    group: "MyAwesomeGroup" # default to None
#    channel-url: "http://127.0.0.1" # defaults to https://open.rocket.chat
#    update-interval: 5 # defaults to 1
#
#  ## Shell (core)
  shell:
#    # optional
#    bot-name: "mybot" # default "opsdroid"
#

## Database modules (optional)

# databases:
#
#  ## Redis (core)
#  redis:
#    host:       "my host"     # (optional) default "localhost"
#    port:       "12345"       # (optional) default "6379"
#    database:   7           # (optional) default 0
#    password:   "pass123"     # (optional) default "None"
#
#  ## Sqlite (core)
#  sqlite:
#    file: "my_file.db"  # (optional) default "~/.opsdroid/sqlite.db"
#    table: "my_table"  # (optional) default "opsdroid"
#
#  ## Mongo (core)
#  mongo:
#    host:       "my host"     # (optional) default "localhost"
#    port:       "12345"       # (optional) default "27017"
#    database:   "mydatabase"  # (optional) default "opsdroid"
#
#  matrix:
#    default_room: "main"
#    single_state_key: "dev.opsdroid.database"
#    should_encrypt: True

## Skill modules
skills:
  ## Dance (https://github.com/opsdroid/skill-dance)
  dance: {}

  ## Hello (https://github.com/opsdroid/skill-hello)
  hello: {}

  ## Loudnoises (https://github.com/opsdroid/skill-loudnoises)
  loudnoises: {}

  ## Seen (https://github.com/opsdroid/skill-seen)
  seen: {}
  # Configurations for other skills uncomment desired skill to activate it.
#
#  ## Cloudhealth (https://github.com/opsdroid/skill-cloudhealth)
#  cloudhealth:
#    # Required
#    chapi-key: ABCDEF123456789  # Cloud Health API key for billing alerts
#    # Optional
#    room: "#monitoring"  # Room to send alert to
#    daily-billing-alerts: true  # Announce the previous day's bill each morning
#    monthly-billing-alerts: true  # Announce the previous month's bill each month
#
#  ## Devtools (https://github.com/opsdroid/skill-devtools)
#  devtools: {}
#
#  ## Dialogflow (https://github.com/opsdroid/skill-dialogflow)
#  dialogflow:
#    include:
#      - smalltalk
#    exclude:
#      - smalltalk.agent
#
#  ## Food (https://github.com/opsdroid/skill-food)
#  food:
#    api-key: "myapikeyfromfood2fork"  # Required
#
#  ## Github (https://github.com/opsdroid/skill-github)
#  github: {}
#
#  ## Google it (https://github.com/opsdroid/skill-google-it)
#  google-it:
#    # Use Google search engine (Default)
#    engine-url: https://www.google.co.uk/
#    query-arg: search?q=
#    # Other search engines that can be used (keep only one uncommented at a time)
#    # Use Bing search engine
#  # engine-url: https://www.bing.com/
#  # query-arg: search?=
#    # Use DuckDuckGo search engine
#  # engine-url: https://duckduckgo.com/
#  # query-arg: ?q=
#    # Use Yahoo search engine
#  # engine-url: http://search.yahoo.com/
#  # query-arg: search?p=
#    # Use Aol search engine
#  # engine-url: https://search.aol.co.uk/aol/
#  # query-arg: search?query=
#    # Use Ask search engine
#  # engine-url: https://uk.ask.com/
#  # query-arg: web?q=
#    # Use Wolframalpha search engine
#  # engine-url: https://www.wolframalpha.com/input/
#  # query-arg: ?i=
#
#  ## Grafana (https://github.com/opsdroid/skill-grafana)
#  grafana:
#    room: "#monitoring"  # (Optional) room to send alert to
#
#  ## Hacktoberfest (https://github.com/opsdroid/skill-hacktoberfest)
#  hacktoberfest: {}
#
#  ## Help (https://github.com/opsdroid/skill-help)
#  skill_name <required_parameter> [optional_parameter] - Description of the skill
#
#  ## Homeassistant (https://github.com/opsdroid/skill-homeassistant)
#  homeassistant:
#    # Notification settings
#    room: "#homeassistant"  # (Optional) room to send notifications to
#    # Conversation component passthrough settings
#    conversation-passthrough: false  # Enable/disable the conversation component passthrough
#    hass-url: "http://127.0.0.1:8123"  # The URL of your Home Assistant
#    hass-password: "YOURPASSWORD"  # Your Home Assistant auth password
#
#  ## Iss (https://github.com/opsdroid/skill-iss)
#  iss:
#    # Required
#    api-key: "mygooglemapsapikey"
#    # Optional
#    zoom: "5"
#    map-size: "1024x768"
#    map-type: "hybrid" # hybrid, satellite or roadmap
#
#  ## Magpi (https://github.com/opsdroid/skill-magpi)
#  magpi:
#    room: "#raspberrypi"  # (Optional) room to send notifications to
#
#  ## Please stand by (https://github.com/opsdroid/skill-please-stand-by)
#  please-stand-by: {}
#
#  ## Random (https://github.com/opsdroid/skill-random)
#  random: {}
#
#  ## Speakingclock (https://github.com/opsdroid/skill-speakingclock)
#  speakingclock: {}
#
#  ## Travis (https://github.com/opsdroid/skill-travis)
#  travis:
#    room: "#monitoring"  # (Optional) room to send alert to
#    travis_endpoint: "org"  # (Optional) endpoint for travis, change to "com" if using enterprise Travis CI
#
#  ## Vault (https://github.com/opsdroid/skill-vault)
#  vault:
#    # Required
#    vault-url: https://vault.example.com:8443
#    vault-token: aabbccddee1122334455
#    # Optional
#    announce-on-seal: false  # Announce the vault status in the default room on seal
#    announce-sealed: true  # Announce the vault is sealed hourly
#    announce-unsealed: false  # Announce the vault is unsealed hourly
#
#  ## Weather (https://github.com/opsdroid/skill-weather)
#  weather:
#    # Required
#    city: London,UK    # For accuracy use {city},{country code}
#    unit: metric       # Choose metric/imperial
#    api-key: 6fut9e098d8g90g
#
#  ## Word of the day (https://github.com/opsdroid/skill-word-of-the-day)
#  word-of-the-day: {}
#
#  ## Words (https://github.com/opsdroid/skill-words)
#  words: {}
#


```

## Additional Details
Console Error:
 
ERROR    The following exception was raised while importing connector opsdroid.connector.matrix                                                                                   loader.py:107
                    ERROR    cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)                                                                           loader.py:112
