### ISSUE TITLE
Direct message support for matrix (element) connector

### ISSUE THREAD

**Issue by m-yosefpor** [opsdroid/opsdroid#1938]
# Description

Ability to handle direct messages in matrix. Users should be able to interact with bot in pv for matrix connector (other connectors such as slack and telegram already support this)

**Comment by diegodorgam** [comment]
Having trouble to receive the direct messages also.
Using docker image `opsdroid/opsdroid:latest` running opsdroid connected to my self hosted matrix server, with the configuration:

```
connectors:
  matrix:
    mxid: "@droid:chat.domain.com"
    password: "<REDACTED>"
    rooms:
      main: '#geral:chat.domain.com'
    homeserver: "https://chat.domain.com"
    nick: "Molon Droid"
    room_specific_nicks: False  
    device_name: "opsdroid"
    enable_encryption: True
    device_id: "opsdroid" 
    store_path: "/home/opsdroid/store" 
```

I can receive and send messages from any public or private(not encrypted) room, but from DM generates this error:

```
droid       | Traceback (most recent call last):
droid       |   File "/usr/local/lib/python3.9/site-packages/opsdroid/connector/matrix/connector.py", line 319, in _parse_sync_response
droid       |     event = self.connection.decrypt_event(event)
droid       |   File "/usr/local/lib/python3.9/site-packages/nio/client/base_client.py", line 115, in inner
droid       |     return fn(self, *args, **kwargs)
droid       |   File "/usr/local/lib/python3.9/site-packages/nio/client/base_client.py", line 641, in decrypt_event
droid       |     return self.olm.decrypt_megolm_event(event)
droid       |   File "/usr/local/lib/python3.9/site-packages/nio/crypto/olm_machine.py", line 1525, in decrypt_megolm_event
droid       |     raise EncryptionError(message)
droid       | nio.exceptions.EncryptionError: Error decrypting megolm event, no session found with session id PVa5IgZQa4eIIR+UXtttgNq3c23JTIQlEBCtset2DKs for room !FxdJJEGABYMhOhgVKt:chat.domain.com
```

Any ideas on how to solve it?
