### ISSUE TITLE
Allow usage of env vars in config

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#194]
The configuration should be parsed for environment variables when loaded. This would allow for secrets like api keys to be kept outside of the opsdroid configuration.

#### Example

```yaml
connectors:
  - name: slack
    default-room: '#general'
    bot-name: "opsdroid"
    icon-emoji: ":robot:"
    api-token: "$SLACK_API_KEY"
```
In this example `$SLACK_API_KEY` would be replaced with the contents of the environment variable of the same name.
