### ISSUE TITLE
Help with configure file

### ISSUE THREAD

**Issue by ZoeyKats** [opsdroid/opsdroid#1981]
Hello, 
This is not a bug report. I am currently working on a new skill for opsdroid, my code is almost ready and all i need to do is to combine it with the rest of the code (opsdroid code). I tried to edit the configuration file just like i saw in the video: 
https://www.youtube.com/watch?v=JKeRBWXWZHk

Now the problem is, i keep getting this error when i try to run opsdroid 

expected 'document start', but found 'block mapping start'
  in "/home/zoey/.config/opsdroid/configuration.yaml", line 114, column 1

Could someone please help me, so that i can run my code and submit a pull request?

PS my first language is not english, so excuse me if my english is not so good

**Comment by FabioRosado** [comment]
Hello @ZoeyKats  👋 

Can you share your `config.yaml` file here?

From the error code that you shared, it seems that you may have issues with spacing. YAML files only accept two spaces (no tabs), can you check your spaces?

If you are able to share the config file it will be easier to see the issue. Alternatively, you could try one of the yaml linting tools online such as https://www.yamllint.com/ to see if it helps you further 😄

**Comment by ZoeyKats** [comment]
Here is my yaml file. I was not sure how exactly i was supposed to send it so i just copy-pasted it on a text file. I tried to figure the error out, but it is actually the first time i work on a yaml file, so i don't have good knowledge.
[my_yaml_file.txt](https://github.com/opsdroid/opsdroid/files/10514199/my_yaml_file.txt)
Thank you for the help!

**Comment by FabioRosado** [comment]
Thank you for the file, the `logging` section is indented with tabs. It must be indented with spaces. Also `logging` shouldn't be indented, instead of:

```yaml
## Set the logging level
  logging:
#   level: info
#   path: opsdroid.log
#   rich: false
    console: false
#   extended: false
```

It needs to be:

```yaml

## Set the logging level
logging:
#   level: info
#   path: opsdroid.log
#   rich: false
  console: false
#   extended: false
```

Hope this helps
