### ISSUE TITLE
[Matrix Connector] Couldn't read a file uploaded in private rooms

### ISSUE THREAD

**Issue by manueldavid123** [opsdroid/opsdroid#1991]
# Description
When I try to read the file in a private room, the byte representation appears encrypted. However, when I run it on a public room, I don't have that problem and I can read the file without problems.

## Steps to Reproduce
Upload a txt file with any content to a private room. A skill with match_event(File) decorator will receive the event. When the method "get_file_bytes()" is called, it returns the content encrypted

## Expected Functionality
The method get_file_bytes() should return the bytes representation of the file.

## Experienced Functionality
The method get_file_bytes() returns the bytes representation of the file encrypted.

## Versions
- **Opsdroid version:** 0.28.0
- **Python version:** 3.9.6
- **OS/Docker version:** opsdroid/opsdroid:latest

## Configuration File
Please include your version of the configuration file below.

```yaml
connectors:
  matrix:
    # Required
    mxid: "user"
    password: "pass"
    rooms:
      'main': 'room'
    homeserver: "https://matrix.org"
    enable_encryption: True
    device_id: "device"
    store_path: /home/opsdroid/.keys/
    room_specific_nicks: False

databases:
  matrix:
```
