### ISSUE TITLE
Support for `apiai` in the config has broken

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#306]
# Description
Since Api.ai was renamed to Dialogflow in #294 any config file with a parser with the name set to `apiai` will not load.

This is bit of a harsh break and it should probably still work for a while and just show a deprecation message.

## Steps to Reproduce
Configure the Dialogflow paser with the old name of `apiai`

## Expected Functionality
It should still work but show a deprecation warning.

## Experienced Functionality
The parser is not enabled.

## Versions
- **Opsdroid version:** v0.9.1-37-g7e2a067 (master)
- **Python version:** 3.5.4
- **OS/Docker version:** macOS High Sierra

## Configuration File
Please include your version of the configuration file bellow.

```yaml
##                      _           _     _
##   ___  _ __  ___  __| |_ __ ___ (_) __| |
##  / _ \| '_ \/ __|/ _` | '__/ _ \| |/ _` |
## | (_) | |_) \__ \ (_| | | | (_) | | (_| |
##  \___/| .__/|___/\__,_|_|  \___/|_|\__,_|
##       |_|
##                   __ _
##   ___ ___  _ __  / _(_) __ _
##  / __/ _ \| '_ \| |_| |/ _` |
## | (_| (_) | | | |  _| | (_| |
##  \___\___/|_| |_|_| |_|\__, |
##                        |___/
##
## A default config file to use with opsdroid

## Set the logging level
# logging:
#   level: info
#   path: opsdroid.log
#   console: true

## Set the location for opsdroid to install modules
# module-path: "."

## Show welcome message
welcome-message: true

## Configure the web server
# web:
#   host: '127.0.0.1'
#   port: 8080
#   ssl:
#     cert: /path/to/cert.pem
#     key: /path/to/key.pem

## Parsers
parsers:
  - name: apiai
    access-token: $DIALOGFLOW_ACCESS_TOKEN
    min-score: 0.6

## Connector modules
connectors:
  - name: shell
  - name: websocket

## Skill modules
skills:

  ## Hello world (https://github.com/opsdroid/skill-hello)
  - name: hello

  ## Last seen (https://github.com/opsdroid/skill-seen)
  - name: seen

  ## Dance (https://github.com/opsdroid/skill-dance)
  - name: dance

  ## Loud noises (https://github.com/opsdroid/skill-loudnoises)
  - name: loudnoises
```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

NA
