### ISSUE TITLE
Streamline local skill development in docker

### ISSUE THREAD

**Issue by gabeduke** [opsdroid/opsdroid#384]
# Description
I've been recently playing around w/ Go and they have a clever way to develop locally before pushing up to github. The engine first looks in the GOPATH for the directory structure [github]/[user]/[project] and if there is no local folder structure that matches, it grabs the code from github. 

This same idea could be a very handy way to install skills to a docker container. The repo would still be defined the same in the configuration file, but Opsdroid would first look for the path at `/etc/opsdroid/github/username/skillname`. If found, install the requirements & skill. If that path does not exist then it would grab it from Github. This could drastically simplify skill development if a user could mount their `skills/` directory directly to the docker container and not have to worry about setting up an environment. Let me know what you think!

Thanks!

**Comment by jacobtomlinson** [comment]
I do like the way go manages dependencies but I'm not sure I follow exactly how that would be used in opsdroid. 

Could you give an example of the config and describe what would happen in that instance?

**Comment by gabeduke** [comment]
This is how I would imagine the directory tree and config looking. You would keep the key value the same for resources (`repo: github.user.project`). Opsdroid loader would just first search for that path locally before reaching out to the url. The repository would still be installed to the code base as part of opsdroid starting up, which would be the key difference between how the `path:` key works. The example below handles some scenarios that aren't necessary but would be handy (parsing out https:// and searching for local paths, and calling out over http(s) to repositories that don't have the protocol defined but don't exist as local paths). 

### directory tree
```.
├── configuration.yaml
├── docker-compose.yaml
└── skills
    ├── github.com
    │  └── username
    │      └── skill_1
    └── gitlab.com
        └── username
            └── skill_4
```

### configuration.yaml

```yaml
## Skill modules
skills:

  # skill_1 uses the local path from the config directory
  - name: skill_1_local_explicit 
    repo: github.com/username/skill_1

  # skill_2 uses the remote repository because of https
  - name: skill_2_remote_explicit
    repo: https://github.com/username/skill_2

  # skill_3 uses the remote private repository in gitlab because the local path doesnt exist
  - name: skill_3_remote_assumed
    repo: gitlab.com/username/skill_3

  # skill_4 is in development using an alternative repository 
  - name: skill_4_local_explicit
    repo: gitlab.com/username/skill_4

  # skill_5 uses a custom path on the filesystem
  - name: skill_5_local_custom_path
    path: /home/user/custom_path
```

### docker-compose.yaml

```yaml
services:
    rasa:
        container_name: rasa
        image: rasa/rasa_nlu:latest-full
        ports:
        - "5000:5000"
        expose:
        - "5000"
        restart: always
        volumes:
        - /home/username/repos/opsdroid/var/projects:/app/projects
        - /home/username/repos/opsdroid/var/logs:/app/logs
        - /home/username/repos/opsdroid/var/data:/app/data
        environment:
            RASA_TOKEN: xxx_api_token_xxx
    opsdroid:
        container_name: opsdroid
        image: opsdroid/opsdroid:dev
        restart: always
        volumes:
        - /home/username/repos/opsdroid/configuration.yaml:/etc/opsdroid/configuration.yaml:ro
        - /home/username/repos/opsdroid/skills:/etc/opsdroid/skills:ro
version: '3'
```
