### ISSUE TITLE
Lozalize opsdroid

### ISSUE THREAD

**Issue by afibanez** [opsdroid/opsdroid#422]
Opsdroid is designed with English in mind. A developer can write his skills (regex and responses) in any other language, but actually it has some complications:
- Some parts of the core code assume English (see [this](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/core.py#L223)  or [this](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/parsers/recastai.py#L15) examples)
- As a developer you could want have your skill ready for multiple languages:
    - But you can only have one matcher, and write a regexpr ready for various languages it's hard and difficult to mantain
    - And there is no system to translate the answer strings, so it has to be implemented in every skill that need it

So let's discuss what we need to do to go multilanguage (i already used some @jacobtomlinson ideas)

Breaking changes
----------------
The idea of the multi language design is to don't break anything. So if you don't change the language, Opsdroid has to assume english and work as normally.

Configuration
-------------
We need a new `language` configuration item, that can be filled with any [ISO 693-1 two-letter code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes). By default it will be `en`.

Core localization
-----------------
We need to use some Python translation library. In my opinion, we should use the [gettext](https://docs.python.org/3/library/gettext.html) library, it is extended, easy to use, and in standard libraries. [Here](https://inventwithpython.com/blog/2014/12/20/translate-your-python-3-program-with-the-gettext-module/) is a post explaining the usage.

So the rule should be mark as translatable every string that can be read by the end user through the chat (like the Whoops error).

Parser/Matcher localization
---------------------------
Now we have different behaviours:
- For `always` or `crontab` there is no problem.
- For `regex` we should add some extra decorators with the locale code at the end (for example `@match_regex_es`). The basic decordator will be mandatory, and it will point always to english. And if the configurated language is not defined by a decorator, it will default to english. For example, for the `skill-hello`, it can be like:
```python
@match_regex(r'hi|hello|hey|hallo')
@match_regex_es(r'hola|buenas|saludos')
async def hello(opsdroid, config, message):
    [...]
```
- `recastai` or `dialogflow` requires a language code to be sent in every request. So my proposal is to define a list of accepted languages (defined by the service) and check if the configurated language is in it. If the configurated language it's not suported by the service, fallback to english.
- `luisai` or `witai` don't recieve a language code in the request. Instead, you need to configure the language as a configuration item on the service. So here, if you need various languages, you need various endpoints. So we need to add more configuration items, like:
```yaml
parsers:
    - name: witai
      access-token: XJF475SKGITJ98KHFO
      min-score: 0.6
    - name: witai
      lang: es
      access-token: XJF475JD8DJ2J98F2DX
      min-score: 0.7
    - name: luisai
      appid: "<application-id>"
      appkey: "<subscription-key>"
      verbose: True
      min-score: 0.6
    - name: luisai
      appid: "<application-id>"
      appkey: "<subscription-key>"
      lang: es
      min-score: 0.7
```
- `rasanlu` works locally and depends on us. So the point here is to translate the intents files. By defualt, we have `intents.md` pointing to english. We can also add a lang code at the end to translate it, like `intents_es.md`. But the languages that rasa supports are [limited](https://nlu.rasa.ai/languages.html), so probably we need to define a list and check it (like in `recastai` or `dialogflow`)

Skill answer localization
-------------------------
I think we sould bet for `gettext` too. We need to implement an interface thinking in the skills too, and let every skill module to has his own translations.
Another time, if it's not translated or `gettext` methods are not used, it will not break and default to english.
