### ISSUE TITLE
Change module configuration layout

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#77]
As suggested by @tpowellmeto `connectors`/`databases`/`skills` are all lists of modules. Therefore they should probably be a list in the configuration rather than a dictionary.

This makes empty module configurations easier to read as they are not empty key/value pairs.

Before

```yaml
skills:
  hello:
    additionalconfigitem: "value"
  seen:
  dance:
  loudnoises:
```

After
```yaml
skills:
  - name: hello
    additionalconfigitem: "value"
  - name: seen
  - name: dance
  - name: loudnoises
```

**Comment by jacobtomlinson** [comment]
This should potentially apply to parsers too as that is a list of things. However parsers are builtin to the core and are less custom.

**Comment by jacobtomlinson** [comment]
I wasn't good at YAML when I wrote this. Empty key-pairs can be represented better with an empty dict `{}`.

```yaml
skills:
  hello:
    additionalconfigitem: "value"
  seen: {}
  dance: {}
  loudnoises: {}
```
