### ISSUE TITLE
Documentation is not clear about the docker volume configuration.

### ISSUE THREAD

**Issue by AndresCidoncha** [opsdroid/opsdroid#781]
# Description
Using the documentation steps for launch opsdroid in Docker, can't load my custom configuration.

## Steps to Reproduce
1. Create a configuration file named `configuration.yaml`.
2. Run `docker run --rm -it -v $(pwd)/configuration.yaml:/etc/opsdroid/configuration.yaml:ro opsdroid/opsdroid:dev`

## Expected Functionality
The documentation should explain that `/path/to/configuration.yaml` must be the folder where the config file is, not the file path. Docker volumes maps folders, not files.

## Experienced Functionality
The docker volume option creates a folder called `configuration.yml` inside `/etc/opsdroid` so the default configuration is loaded.

## Versions
- **Opsdroid version:** opsdroid 0+unknown (inside the container)
- **Python version:** Python 3.6.7 (inside the container)
- **OS/Docker version:** Docker version 18.06.1-ce, build e68fc7a

## Configuration File
```yaml
welcome-message: true
web:
  host: '0.0.0.0'
  port: 8080
```

## Additional Details
Maybe adding a `docker-compose.yml` using docker configs can avoid problems. I created the file, so I can do a PR if you want.

**Comment by contato318** [comment]
My example (docker-compose.yaml):


```
version: '3'
services:
  bot:
    stdin_open: true
    tty: true
    image: opsdroid/opsdroid:latest
    ports:
       - "8080:8080"
    volumes:
       - ./data/root/:/root/
       - ./data/log/:/var/log/opsdroid/
```
My configuration file (example):  data/root/.config/opsdroid/configuration.yaml

```
logging:
   level: info
   path: /var/log/opsdroid/opsdroid.log
   console: true
web:
   host: '0.0.0.0'
   port: 8080
```
