### ISSUE TITLE
Add filters to logging

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#954]
Currently, opsdroid has a lot of things logging into debug mode, which makes it hard to try and find things while doing the actual debugging.

It would be good to implement filters that could be added to the logging through the `config.yaml` file. 

After sharing this in the channel Jacob suggested to implement filters by creating a class that goes through all those logs and then use the config to add a list of things to filter and that class would check every log against that list and either show that log or drop it.

**Comment by jacobtomlinson** [comment]
Sounds good!

We should add some kind of config option like:

```yaml
logging:
  level: debug
  console: true
  filters:
    - aiosqlite
    - websockets.protocol
```

We would need to implement a log filter class which would compare the log domain with the filter list and return `False` for anything which starts with one of the filters.
