### ISSUE TITLE
Possible to Specify ssh key for private github skill

### ISSUE THREAD

**Issue by jseiser** [opsdroid/opsdroid#980]
# Description
We almost exclusively use private github repo's, in our github enterprise.  It would be ideal if I could load a key into the docker container as a secret or config, and reference it in the configuration to be used when pulling the skill.

## Steps to Reproduce
Currently, unable to pull in a private ssh repo, without rebuilding the docker image

## Expected Functionality
```
skills:
  ## AWX (https://github.com/jseiser/skill-awx)
  - name: awx
    repo: https://github.com/jseiser/skill-nothing.git
    no-cache: true
    key: /root/.config/opsroid/whatever.pem
```

## Experienced Functionality
Explain what happened instead(Please include the debug log).

## Versions
- **Opsdroid version:**
- **Python version:**
- **OS/Docker version:**

## Configuration File
Please include your version of the configuration file bellow.

```yaml
# Your code goes here.

```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

**Comment by jacobtomlinson** [comment]
This is an interesting request and something we would definitely like to support!

Doing some quick research it seems you cannot tell git which keys to use directly, it's all down to your ssh config. 

One option could be to set the `GIT_SSH_COMMAND` env var to override gits ssh command before subprocess calls git. Then clear the env var again.

```
GIT_SSH_COMMAND='ssh -i /root/.config/opsroid/whatever.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
```

**Comment by jseiser** [comment]
Something like this?  I assume, determining the key path should probably be done somewhere besides '_install_git_module'

```
@staticmethod
def git_clone(git_url, install_path, branch, key_path=None):
    """Clone a git repo to a location and wait for finish.
    Args:
        git_url: The url to the git repository
        install_path: Location where the git repository will be cloned
        branch: The branch to be cloned
        key_path: SSH key for git repository
    """
    git_env = os.environ.copy()
    if key_path:
        git_env['GIT_SSH_COMMAND'] = f"ssh -i {key_path} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

    process = subprocess.Popen(
        ["git", "clone", "-b", branch, git_url, install_path],
        shell=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=git_env
    )
    Loader._communicate_process(process)

def _install_git_module(self, config):
    """Install a module from a git repository.
    Args:
        self: instance method
        config: dict of module config fields
    """
    if config is not None and "repo" in config:
        git_url = config["repo"]
        key_path = None
        if "key_path" in config:
            key_path = config["key_path"]
    else:
        git_url = DEFAULT_GIT_URL + config["type"] + "-" + config["name"] + ".git"

    if any(prefix in git_url for prefix in ["http", "https", "ssh"]):
        # TODO Test if url or ssh path exists
        # TODO Handle github authentication
        _LOGGER.info(_("Cloning %s from remote repository"), config["name"])
        self.git_clone(git_url, config["install_path"], config["branch"], key_path)
    else:
        if os.path.isdir(git_url):
            _LOGGER.debug(_("Cloning %s from local repository"), config["name"])
            self.git_clone(git_url, config["install_path"], config["branch"])
        else:
            _LOGGER.error(_("Could not find local git repo %s"), git_url)
```

Then docker-compose.yml

```
    configs:
      -  source: repo_key
         target: /root/.config/opsdroid/mykey.pem
         mode: 0400
         uid: '999' <-- would need to actually determine the users uid/guid
         gid: '999'

configs:
  repo_key:
    file: ./config/mykey.pem
```

Config:

```
  - name: awx
    repo: https://github.com/jseiser/skill-awx.git
    no-cache: true
    key_path: /root/.config/opsdroid/mykey.pem
```
